/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "MockSS_grazyna_hal.h"

static const char* CMockString_SS_grazyna_crc_hal = "SS_grazyna_crc_hal";
static const char* CMockString_SS_grazyna_init_hal = "SS_grazyna_init_hal";
static const char* CMockString_SS_grazyna_receive_hal = "SS_grazyna_receive_hal";
static const char* CMockString_SS_grazyna_transmit_hal = "SS_grazyna_transmit_hal";
static const char* CMockString_data = "data";
static const char* CMockString_huart = "huart";
static const char* CMockString_len = "len";
static const char* CMockString_length = "length";

typedef struct _CMOCK_SS_grazyna_init_hal_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  void* Expected_huart;
  int Expected_huart_Depth;

} CMOCK_SS_grazyna_init_hal_CALL_INSTANCE;

typedef struct _CMOCK_SS_grazyna_receive_hal_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t* Expected_data;
  uint16_t Expected_length;
  int Expected_data_Depth;

} CMOCK_SS_grazyna_receive_hal_CALL_INSTANCE;

typedef struct _CMOCK_SS_grazyna_transmit_hal_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t* Expected_data;
  uint16_t Expected_length;
  int Expected_data_Depth;

} CMOCK_SS_grazyna_transmit_hal_CALL_INSTANCE;

typedef struct _CMOCK_SS_grazyna_crc_hal_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;
  uint32_t* Expected_data;
  uint32_t Expected_len;
  int Expected_data_Depth;

} CMOCK_SS_grazyna_crc_hal_CALL_INSTANCE;

static struct MockSS_grazyna_halInstance
{
  CMOCK_MEM_INDEX_TYPE SS_grazyna_init_hal_CallInstance;
  CMOCK_MEM_INDEX_TYPE SS_grazyna_receive_hal_CallInstance;
  CMOCK_MEM_INDEX_TYPE SS_grazyna_transmit_hal_CallInstance;
  CMOCK_MEM_INDEX_TYPE SS_grazyna_crc_hal_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockSS_grazyna_hal_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.SS_grazyna_init_hal_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SS_grazyna_init_hal);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.SS_grazyna_receive_hal_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SS_grazyna_receive_hal);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.SS_grazyna_transmit_hal_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SS_grazyna_transmit_hal);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.SS_grazyna_crc_hal_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SS_grazyna_crc_hal);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void MockSS_grazyna_hal_Init(void)
{
  MockSS_grazyna_hal_Destroy();
}

void MockSS_grazyna_hal_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void SS_grazyna_init_hal(void* huart)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SS_grazyna_init_hal_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SS_grazyna_init_hal);
  cmock_call_instance = (CMOCK_SS_grazyna_init_hal_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SS_grazyna_init_hal_CallInstance);
  Mock.SS_grazyna_init_hal_CallInstance = CMock_Guts_MemNext(Mock.SS_grazyna_init_hal_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_SS_grazyna_init_hal,CMockString_huart);
    if (cmock_call_instance->Expected_huart == NULL)
      { UNITY_TEST_ASSERT_NULL(huart, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_huart, huart, cmock_call_instance->Expected_huart_Depth, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SS_grazyna_init_hal(CMOCK_SS_grazyna_init_hal_CALL_INSTANCE* cmock_call_instance, void* huart, int huart_Depth)
{
  cmock_call_instance->Expected_huart = huart;
  cmock_call_instance->Expected_huart_Depth = huart_Depth;
}

void SS_grazyna_init_hal_CMockExpect(UNITY_LINE_TYPE cmock_line, void* huart)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SS_grazyna_init_hal_CALL_INSTANCE));
  CMOCK_SS_grazyna_init_hal_CALL_INSTANCE* cmock_call_instance = (CMOCK_SS_grazyna_init_hal_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SS_grazyna_init_hal_CallInstance = CMock_Guts_MemChain(Mock.SS_grazyna_init_hal_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_SS_grazyna_init_hal(cmock_call_instance, huart, 1);
}

void SS_grazyna_init_hal_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, void* huart, int huart_Depth)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SS_grazyna_init_hal_CALL_INSTANCE));
  CMOCK_SS_grazyna_init_hal_CALL_INSTANCE* cmock_call_instance = (CMOCK_SS_grazyna_init_hal_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SS_grazyna_init_hal_CallInstance = CMock_Guts_MemChain(Mock.SS_grazyna_init_hal_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_SS_grazyna_init_hal(cmock_call_instance, huart, huart_Depth);
}

void SS_grazyna_receive_hal(uint8_t* data, uint16_t length)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SS_grazyna_receive_hal_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SS_grazyna_receive_hal);
  cmock_call_instance = (CMOCK_SS_grazyna_receive_hal_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SS_grazyna_receive_hal_CallInstance);
  Mock.SS_grazyna_receive_hal_CallInstance = CMock_Guts_MemNext(Mock.SS_grazyna_receive_hal_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_SS_grazyna_receive_hal,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_data, data, cmock_call_instance->Expected_data_Depth, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_SS_grazyna_receive_hal,CMockString_length);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_length, length, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SS_grazyna_receive_hal(CMOCK_SS_grazyna_receive_hal_CALL_INSTANCE* cmock_call_instance, uint8_t* data, int data_Depth, uint16_t length)
{
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->Expected_data_Depth = data_Depth;
  cmock_call_instance->Expected_length = length;
}

void SS_grazyna_receive_hal_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t* data, uint16_t length)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SS_grazyna_receive_hal_CALL_INSTANCE));
  CMOCK_SS_grazyna_receive_hal_CALL_INSTANCE* cmock_call_instance = (CMOCK_SS_grazyna_receive_hal_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SS_grazyna_receive_hal_CallInstance = CMock_Guts_MemChain(Mock.SS_grazyna_receive_hal_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_SS_grazyna_receive_hal(cmock_call_instance, data, 1, length);
}

void SS_grazyna_receive_hal_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, uint8_t* data, int data_Depth, uint16_t length)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SS_grazyna_receive_hal_CALL_INSTANCE));
  CMOCK_SS_grazyna_receive_hal_CALL_INSTANCE* cmock_call_instance = (CMOCK_SS_grazyna_receive_hal_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SS_grazyna_receive_hal_CallInstance = CMock_Guts_MemChain(Mock.SS_grazyna_receive_hal_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_SS_grazyna_receive_hal(cmock_call_instance, data, data_Depth, length);
}

void SS_grazyna_transmit_hal(uint8_t* data, uint16_t length)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SS_grazyna_transmit_hal_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SS_grazyna_transmit_hal);
  cmock_call_instance = (CMOCK_SS_grazyna_transmit_hal_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SS_grazyna_transmit_hal_CallInstance);
  Mock.SS_grazyna_transmit_hal_CallInstance = CMock_Guts_MemNext(Mock.SS_grazyna_transmit_hal_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_SS_grazyna_transmit_hal,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_data, data, cmock_call_instance->Expected_data_Depth, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_SS_grazyna_transmit_hal,CMockString_length);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_length, length, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SS_grazyna_transmit_hal(CMOCK_SS_grazyna_transmit_hal_CALL_INSTANCE* cmock_call_instance, uint8_t* data, int data_Depth, uint16_t length)
{
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->Expected_data_Depth = data_Depth;
  cmock_call_instance->Expected_length = length;
}

void SS_grazyna_transmit_hal_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t* data, uint16_t length)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SS_grazyna_transmit_hal_CALL_INSTANCE));
  CMOCK_SS_grazyna_transmit_hal_CALL_INSTANCE* cmock_call_instance = (CMOCK_SS_grazyna_transmit_hal_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SS_grazyna_transmit_hal_CallInstance = CMock_Guts_MemChain(Mock.SS_grazyna_transmit_hal_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_SS_grazyna_transmit_hal(cmock_call_instance, data, 1, length);
}

void SS_grazyna_transmit_hal_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, uint8_t* data, int data_Depth, uint16_t length)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SS_grazyna_transmit_hal_CALL_INSTANCE));
  CMOCK_SS_grazyna_transmit_hal_CALL_INSTANCE* cmock_call_instance = (CMOCK_SS_grazyna_transmit_hal_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SS_grazyna_transmit_hal_CallInstance = CMock_Guts_MemChain(Mock.SS_grazyna_transmit_hal_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_SS_grazyna_transmit_hal(cmock_call_instance, data, data_Depth, length);
}

uint32_t SS_grazyna_crc_hal(uint32_t* data, uint32_t len)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SS_grazyna_crc_hal_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SS_grazyna_crc_hal);
  cmock_call_instance = (CMOCK_SS_grazyna_crc_hal_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SS_grazyna_crc_hal_CallInstance);
  Mock.SS_grazyna_crc_hal_CallInstance = CMock_Guts_MemNext(Mock.SS_grazyna_crc_hal_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_SS_grazyna_crc_hal,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_data, data, cmock_call_instance->Expected_data_Depth, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_SS_grazyna_crc_hal,CMockString_len);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_len, len, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SS_grazyna_crc_hal(CMOCK_SS_grazyna_crc_hal_CALL_INSTANCE* cmock_call_instance, uint32_t* data, int data_Depth, uint32_t len)
{
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->Expected_data_Depth = data_Depth;
  cmock_call_instance->Expected_len = len;
}

void SS_grazyna_crc_hal_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t* data, uint32_t len, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SS_grazyna_crc_hal_CALL_INSTANCE));
  CMOCK_SS_grazyna_crc_hal_CALL_INSTANCE* cmock_call_instance = (CMOCK_SS_grazyna_crc_hal_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SS_grazyna_crc_hal_CallInstance = CMock_Guts_MemChain(Mock.SS_grazyna_crc_hal_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_SS_grazyna_crc_hal(cmock_call_instance, data, 1, len);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void SS_grazyna_crc_hal_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t* data, int data_Depth, uint32_t len, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SS_grazyna_crc_hal_CALL_INSTANCE));
  CMOCK_SS_grazyna_crc_hal_CALL_INSTANCE* cmock_call_instance = (CMOCK_SS_grazyna_crc_hal_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SS_grazyna_crc_hal_CallInstance = CMock_Guts_MemChain(Mock.SS_grazyna_crc_hal_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_SS_grazyna_crc_hal(cmock_call_instance, data, data_Depth, len);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

