/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSS_COM_H
#define _MOCKSS_COM_H

#include "unity.h"
#include "SS_com.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MockSS_com_Init(void);
void MockSS_com_Destroy(void);
void MockSS_com_Verify(void);


typedef void(*cmock_SS_com_func_ptr1)(ComFrame*);


#define SS_com_add_sender_ExpectAndReturn(cmock_retval) SS_com_add_sender_CMockExpectAndReturn(__LINE__, cmock_retval)
void SS_com_add_sender_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, QueueHandle_t cmock_to_return);
#define SS_com_add_to_queue_Expect(frame, sender_fun, queue) SS_com_add_to_queue_CMockExpect(__LINE__, frame, sender_fun, queue)
void SS_com_add_to_queue_CMockExpect(UNITY_LINE_TYPE cmock_line, ComFrame* frame, cmock_SS_com_func_ptr1 sender_fun, QueueHandle_t queue);
#define SS_com_add_to_queue_ExpectWithArray(frame, frame_Depth, sender_fun, queue) SS_com_add_to_queue_CMockExpectWithArray(__LINE__, frame, frame_Depth, sender_fun, queue)
void SS_com_add_to_queue_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, ComFrame* frame, int frame_Depth, cmock_SS_com_func_ptr1 sender_fun, QueueHandle_t queue);
#define SS_com_message_received_Expect(frame) SS_com_message_received_CMockExpect(__LINE__, frame)
void SS_com_message_received_CMockExpect(UNITY_LINE_TYPE cmock_line, ComFrame* frame);
#define SS_com_message_received_ExpectWithArray(frame, frame_Depth) SS_com_message_received_CMockExpectWithArray(__LINE__, frame, frame_Depth)
void SS_com_message_received_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, ComFrame* frame, int frame_Depth);
#define SS_com_init_Expect(board) SS_com_init_CMockExpect(__LINE__, board)
void SS_com_init_CMockExpect(UNITY_LINE_TYPE cmock_line, ComBoardID board);
#define SS_com_transmit_Expect(frame) SS_com_transmit_CMockExpect(__LINE__, frame)
void SS_com_transmit_CMockExpect(UNITY_LINE_TYPE cmock_line, ComFrame* frame);
#define SS_com_transmit_ExpectWithArray(frame, frame_Depth) SS_com_transmit_CMockExpectWithArray(__LINE__, frame, frame_Depth)
void SS_com_transmit_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, ComFrame* frame, int frame_Depth);
#define SS_com_handle_frame_ExpectAndReturn(frame, cmock_retval) SS_com_handle_frame_CMockExpectAndReturn(__LINE__, frame, cmock_retval)
void SS_com_handle_frame_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ComFrame* frame, ComStatus cmock_to_return);
#define SS_com_handle_frame_ExpectWithArrayAndReturn(frame, frame_Depth, cmock_retval) SS_com_handle_frame_CMockExpectWithArrayAndReturn(__LINE__, frame, frame_Depth, cmock_retval)
void SS_com_handle_frame_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, ComFrame* frame, int frame_Depth, ComStatus cmock_to_return);
#define SS_com_handle_action_ExpectAndReturn(frame, cmock_retval) SS_com_handle_action_CMockExpectAndReturn(__LINE__, frame, cmock_retval)
void SS_com_handle_action_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ComFrame* frame, ComStatus cmock_to_return);
#define SS_com_handle_action_ExpectWithArrayAndReturn(frame, frame_Depth, cmock_retval) SS_com_handle_action_CMockExpectWithArrayAndReturn(__LINE__, frame, frame_Depth, cmock_retval)
void SS_com_handle_action_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, ComFrame* frame, int frame_Depth, ComStatus cmock_to_return);
#define SS_com_handle_request_ExpectAndReturn(frame, cmock_retval) SS_com_handle_request_CMockExpectAndReturn(__LINE__, frame, cmock_retval)
void SS_com_handle_request_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ComFrame* frame, ComStatus cmock_to_return);
#define SS_com_handle_request_ExpectWithArrayAndReturn(frame, frame_Depth, cmock_retval) SS_com_handle_request_CMockExpectWithArrayAndReturn(__LINE__, frame, frame_Depth, cmock_retval)
void SS_com_handle_request_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, ComFrame* frame, int frame_Depth, ComStatus cmock_to_return);
#define SS_com_handle_service_ExpectAndReturn(frame, cmock_retval) SS_com_handle_service_CMockExpectAndReturn(__LINE__, frame, cmock_retval)
void SS_com_handle_service_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ComFrame* frame, ComStatus cmock_to_return);
#define SS_com_handle_service_ExpectWithArrayAndReturn(frame, frame_Depth, cmock_retval) SS_com_handle_service_CMockExpectWithArrayAndReturn(__LINE__, frame, frame_Depth, cmock_retval)
void SS_com_handle_service_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, ComFrame* frame, int frame_Depth, ComStatus cmock_to_return);
#define SS_com_add_payload_to_frame_Expect(frame, type, payload) SS_com_add_payload_to_frame_CMockExpect(__LINE__, frame, type, payload)
void SS_com_add_payload_to_frame_CMockExpect(UNITY_LINE_TYPE cmock_line, ComFrame* frame, ComDataType type, void* payload);
#define SS_com_add_payload_to_frame_ExpectWithArray(frame, frame_Depth, type, payload, payload_Depth) SS_com_add_payload_to_frame_CMockExpectWithArray(__LINE__, frame, frame_Depth, type, payload, payload_Depth)
void SS_com_add_payload_to_frame_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, ComFrame* frame, int frame_Depth, ComDataType type, void* payload, int payload_Depth);
#define SS_com_main_Expect() SS_com_main_CMockExpect(__LINE__)
void SS_com_main_CMockExpect(UNITY_LINE_TYPE cmock_line);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
