version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: ch4ron/stm32-ci
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote --init --recursive
      - run:
          name: "Run tests"
          command:
              SS-test/run_tests.sh
      - run:
          name: "Create build directory"
          command: mkdir cmake-build && cd cmake-build && cmake ../
      - run:
          name: "Build Kromek"
          command:
              make -C cmake-build kromek.elf
      - codecov/upload:
          file: "!FreeRTOS"
          flags: "coverage"
