# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: ch4ron/stm32-ci
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: test
          command:
              JUMPER=jumper python build.py kromek simulate --verbose
      - store_artifacts:
          path: BUILD/
