version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: ch4ron/stm32-ci
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote --init --recursive
      - run:
          name: "Create build directory"
          command: mkdir cmake-build && cd cmake-build && cmake ../
      - run:
          name: "Create test build directory"
          command: mkdir cmake-build-test && cd cmake-build-test && cmake -DCMAKE_BUILD_TYPE=Test ../
      - run:
          name: "Build Kromek"
          command:
              make -C cmake-build kromek.elf
      - run:
          name: "Build Staszek"
          command:
              make -C cmake-build staszek.elf
      - run:
          name: "Build Pauek"
          command:
              make -C cmake-build pauek.elf
      - run:
          name: "Build Kromek test"
          command:
              make -C cmake-build-test kromek.elf
      - run:
          name: "Build Staszek test"
          command:
              make -C cmake-build-test staszek.elf
      - run:
          name: "Build Pauek test"
          command:
              make -C cmake-build-test pauek.elf
      - run:
          name: "Run tests"
          command:
              make -C cmake-build test
      - codecov/upload:
          file: "!FreeRTOS"
          flags: "coverage"
