version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: ch4ron/stm32-ci
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote --init --recursive
      # - run:
          # name: "Build Staszek"
          # command:
              # ./build.py staszek build
      # - run:
          # name: "Build Pauek"
          # command:
              # ./build.py pauek build
      # - run:
          # name: "Build Czapla"
          # command:
              # ./build.py czapla build
      - run:
          name: "Build Kromek"
          command:
              ./build.py kromek build
      - run:
          name: "Run tests"
          command:
              SS-test/run_tests.sh
      - codecov/upload:
          file: "!FreeRTOS"
          flags: "coverage"
      - store_artifacts:
          path: BUILD/
