version: 2.1
jobs:
  build:
    docker:
      - image: ch4ron/stm32-ci
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: "Build Staszek"
          command:
              ./build.py staszek build
      - run:
          name: "Build Pauek"
          command:
              ./build.py pauek build
      - run:
          name: "Build Czapla"
          command:
              ./build.py czapla build
      - run:
          name: "Simulate Kromek"
          command:
              JUMPER=jumper ./build.py kromek simulate --verbose
      - store_artifacts:
          path: BUILD/
