/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKCROUTINE_H
#define _MOCKCROUTINE_H

#include "FreeRTOS.h"
#include "croutine.h"
#include "unity.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockcroutine_Init(void);
void Mockcroutine_Destroy(void);
void Mockcroutine_Verify(void);

#define xCoRoutineCreate_ExpectAndReturn(pxCoRoutineCode, uxPriority, uxIndex, cmock_retval) xCoRoutineCreate_CMockExpectAndReturn(__LINE__, pxCoRoutineCode, uxPriority, uxIndex, cmock_retval)
void xCoRoutineCreate_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, crCOROUTINE_CODE pxCoRoutineCode, UBaseType_t uxPriority, UBaseType_t uxIndex, BaseType_t cmock_to_return);
#define vCoRoutineSchedule_Expect() vCoRoutineSchedule_CMockExpect(__LINE__)
void vCoRoutineSchedule_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define vCoRoutineAddToDelayedList_Expect(xTicksToDelay, pxEventList) vCoRoutineAddToDelayedList_CMockExpect(__LINE__, xTicksToDelay, pxEventList)
void vCoRoutineAddToDelayedList_CMockExpect(UNITY_LINE_TYPE cmock_line, TickType_t xTicksToDelay, List_t* pxEventList);
#define xCoRoutineRemoveFromEventList_ExpectAndReturn(pxEventList, cmock_retval) xCoRoutineRemoveFromEventList_CMockExpectAndReturn(__LINE__, pxEventList, cmock_retval)
void xCoRoutineRemoveFromEventList_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const List_t* pxEventList, BaseType_t cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
