/* AUTOGENERATED FILE. DO NOT EDIT. */
#include "Mocklist.h"

#include <setjmp.h>
#include <stdlib.h>
#include <string.h>

#include "FreeRTOS.h"
#include "cmock.h"

static const char* CMockString_pxItem = "pxItem";
static const char* CMockString_pxItemToRemove = "pxItemToRemove";
static const char* CMockString_pxList = "pxList";
static const char* CMockString_pxNewListItem = "pxNewListItem";
static const char* CMockString_uxListRemove = "uxListRemove";
static const char* CMockString_vListInitialise = "vListInitialise";
static const char* CMockString_vListInitialiseItem = "vListInitialiseItem";
static const char* CMockString_vListInsert = "vListInsert";
static const char* CMockString_vListInsertEnd = "vListInsertEnd";

typedef struct _CMOCK_vListInitialise_CALL_INSTANCE {
    UNITY_LINE_TYPE LineNumber;
    List_t* Expected_pxList;

} CMOCK_vListInitialise_CALL_INSTANCE;

typedef struct _CMOCK_vListInitialiseItem_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  ListItem_t* Expected_pxItem;

} CMOCK_vListInitialiseItem_CALL_INSTANCE;

typedef struct _CMOCK_vListInsert_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  List_t* Expected_pxList;
  ListItem_t* Expected_pxNewListItem;

} CMOCK_vListInsert_CALL_INSTANCE;

typedef struct _CMOCK_vListInsertEnd_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  List_t* Expected_pxList;
  ListItem_t* Expected_pxNewListItem;

} CMOCK_vListInsertEnd_CALL_INSTANCE;

typedef struct _CMOCK_uxListRemove_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  UBaseType_t ReturnVal;
  ListItem_t* Expected_pxItemToRemove;

} CMOCK_uxListRemove_CALL_INSTANCE;

static struct MocklistInstance
{
  CMOCK_MEM_INDEX_TYPE vListInitialise_CallInstance;
  CMOCK_MEM_INDEX_TYPE vListInitialiseItem_CallInstance;
  CMOCK_MEM_INDEX_TYPE vListInsert_CallInstance;
  CMOCK_MEM_INDEX_TYPE vListInsertEnd_CallInstance;
  CMOCK_MEM_INDEX_TYPE uxListRemove_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mocklist_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.vListInitialise_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_vListInitialise);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.vListInitialiseItem_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_vListInitialiseItem);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.vListInsert_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_vListInsert);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.vListInsertEnd_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_vListInsertEnd);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.uxListRemove_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_uxListRemove);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mocklist_Init(void)
{
  Mocklist_Destroy();
}

void Mocklist_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void vListInitialise(List_t* const pxList)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_vListInitialise_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_vListInitialise);
  cmock_call_instance = (CMOCK_vListInitialise_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.vListInitialise_CallInstance);
  Mock.vListInitialise_CallInstance = CMock_Guts_MemNext(Mock.vListInitialise_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_vListInitialise,CMockString_pxList);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pxList), (void*)(pxList), sizeof(List_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_vListInitialise(CMOCK_vListInitialise_CALL_INSTANCE* cmock_call_instance, List_t* const pxList)
{
  cmock_call_instance->Expected_pxList = pxList;
}

void vListInitialise_CMockExpect(UNITY_LINE_TYPE cmock_line, List_t* const pxList)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_vListInitialise_CALL_INSTANCE));
  CMOCK_vListInitialise_CALL_INSTANCE* cmock_call_instance = (CMOCK_vListInitialise_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.vListInitialise_CallInstance = CMock_Guts_MemChain(Mock.vListInitialise_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_vListInitialise(cmock_call_instance, pxList);
}

void vListInitialiseItem(ListItem_t* const pxItem)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_vListInitialiseItem_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_vListInitialiseItem);
  cmock_call_instance = (CMOCK_vListInitialiseItem_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.vListInitialiseItem_CallInstance);
  Mock.vListInitialiseItem_CallInstance = CMock_Guts_MemNext(Mock.vListInitialiseItem_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_vListInitialiseItem,CMockString_pxItem);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pxItem), (void*)(pxItem), sizeof(ListItem_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_vListInitialiseItem(CMOCK_vListInitialiseItem_CALL_INSTANCE* cmock_call_instance, ListItem_t* const pxItem)
{
  cmock_call_instance->Expected_pxItem = pxItem;
}

void vListInitialiseItem_CMockExpect(UNITY_LINE_TYPE cmock_line, ListItem_t* const pxItem)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_vListInitialiseItem_CALL_INSTANCE));
  CMOCK_vListInitialiseItem_CALL_INSTANCE* cmock_call_instance = (CMOCK_vListInitialiseItem_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.vListInitialiseItem_CallInstance = CMock_Guts_MemChain(Mock.vListInitialiseItem_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_vListInitialiseItem(cmock_call_instance, pxItem);
}

void vListInsert(List_t* const pxList, ListItem_t* const pxNewListItem)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_vListInsert_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_vListInsert);
  cmock_call_instance = (CMOCK_vListInsert_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.vListInsert_CallInstance);
  Mock.vListInsert_CallInstance = CMock_Guts_MemNext(Mock.vListInsert_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_vListInsert,CMockString_pxList);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pxList), (void*)(pxList), sizeof(List_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_vListInsert,CMockString_pxNewListItem);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pxNewListItem), (void*)(pxNewListItem), sizeof(ListItem_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_vListInsert(CMOCK_vListInsert_CALL_INSTANCE* cmock_call_instance, List_t* const pxList, ListItem_t* const pxNewListItem)
{
  cmock_call_instance->Expected_pxList = pxList;
  cmock_call_instance->Expected_pxNewListItem = pxNewListItem;
}

void vListInsert_CMockExpect(UNITY_LINE_TYPE cmock_line, List_t* const pxList, ListItem_t* const pxNewListItem)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_vListInsert_CALL_INSTANCE));
  CMOCK_vListInsert_CALL_INSTANCE* cmock_call_instance = (CMOCK_vListInsert_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.vListInsert_CallInstance = CMock_Guts_MemChain(Mock.vListInsert_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_vListInsert(cmock_call_instance, pxList, pxNewListItem);
}

void vListInsertEnd(List_t* const pxList, ListItem_t* const pxNewListItem)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_vListInsertEnd_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_vListInsertEnd);
  cmock_call_instance = (CMOCK_vListInsertEnd_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.vListInsertEnd_CallInstance);
  Mock.vListInsertEnd_CallInstance = CMock_Guts_MemNext(Mock.vListInsertEnd_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_vListInsertEnd,CMockString_pxList);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pxList), (void*)(pxList), sizeof(List_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_vListInsertEnd,CMockString_pxNewListItem);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pxNewListItem), (void*)(pxNewListItem), sizeof(ListItem_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_vListInsertEnd(CMOCK_vListInsertEnd_CALL_INSTANCE* cmock_call_instance, List_t* const pxList, ListItem_t* const pxNewListItem)
{
  cmock_call_instance->Expected_pxList = pxList;
  cmock_call_instance->Expected_pxNewListItem = pxNewListItem;
}

void vListInsertEnd_CMockExpect(UNITY_LINE_TYPE cmock_line, List_t* const pxList, ListItem_t* const pxNewListItem)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_vListInsertEnd_CALL_INSTANCE));
  CMOCK_vListInsertEnd_CALL_INSTANCE* cmock_call_instance = (CMOCK_vListInsertEnd_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.vListInsertEnd_CallInstance = CMock_Guts_MemChain(Mock.vListInsertEnd_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_vListInsertEnd(cmock_call_instance, pxList, pxNewListItem);
}

UBaseType_t uxListRemove(ListItem_t* const pxItemToRemove)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_uxListRemove_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_uxListRemove);
  cmock_call_instance = (CMOCK_uxListRemove_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.uxListRemove_CallInstance);
  Mock.uxListRemove_CallInstance = CMock_Guts_MemNext(Mock.uxListRemove_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_uxListRemove,CMockString_pxItemToRemove);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pxItemToRemove), (void*)(pxItemToRemove), sizeof(ListItem_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_uxListRemove(CMOCK_uxListRemove_CALL_INSTANCE* cmock_call_instance, ListItem_t* const pxItemToRemove)
{
  cmock_call_instance->Expected_pxItemToRemove = pxItemToRemove;
}

void uxListRemove_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ListItem_t* const pxItemToRemove, UBaseType_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_uxListRemove_CALL_INSTANCE));
  CMOCK_uxListRemove_CALL_INSTANCE* cmock_call_instance = (CMOCK_uxListRemove_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.uxListRemove_CallInstance = CMock_Guts_MemChain(Mock.uxListRemove_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_uxListRemove(cmock_call_instance, pxItemToRemove);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(UBaseType_t[sizeof(cmock_to_return) == sizeof(UBaseType_t) ? 1 : -1])); /* add UBaseType_t to :treat_as_array if this causes an error */
}

